### PR TITLE
#157746347 Create User Signup page

### PR DESCRIPTION
**Pull request by blac-siren**
**What does this PR do?**
Design for the user signup page.

**Description of Task to be completed?**
It's only a design for signup page.
Have descriptive form for the user to signup. i.e  full name, email, password input fields.
There is link that will direct user to login.

**How should this be manually tested?**
clone the repository into your local machine.
navigate into UI directory
finally open signup.html file in your browser.

Screenshots (if appropriate)
screenshot at 2018-05-23 21-29-48

### CODE REVIEW

**Comment by gitaumoses4** [comment]
Amazing UI, Loving the use of colors. Well organized form and use of icons.
I'm intrigued. 
Beautiful. :+1:

**Comment by asamisellah** [comment]
Your PR is good. Maybe just add this part  #### What are the relevant pivotal tracker stories?. I love your sign up page

**Comment by blac-siren** [comment]
@gitaumoses4 Thank you

**Comment by blac-siren** [comment]
@asamisellah i'll work on that. Thank you

**Pull request merged**
