### PR TITLE
#157748679 Page where Admin can view all request.

### PR DESCRIPTION
**Pull request by blac-siren**
**What does this PR do?**
Implements a page where Admin can view all request made.

**Description of Task to be completed?**
A well designed sidebar that will allow Admin to sign out or go to dashboard.
A table where admin can view all the request.
A dropdown button that allow Admin to accept or reject request.

**How should this be manually tested?**
clone the repository into your local machine.
open your IDE 
create a new branch
`git checkout -b <new branch>`
`git fetch ft-all-request-157748679`
open all_request.html into your browser.
git chechout -b new-branch
git fetch ft-user-all-requests-157746115
open user_all_requests.html in your browser

**What are the relevant pivotal tracker stories?**
#157748679 

Screenshots (if available)
image

### CODE REVIEW

**Comment by asamisellah** [comment]
Lovely UI. The form is descriptive. Good PR. I throw back the question, have you been able to make your page responsive?

**Comment by joelmachango** [comment]
@blac-siren Beautiful UI. Change the base branch to develop. Don't merge to master.

**Comment by blac-siren** [comment]
oooh yeah thank you @joelmachango.

**Comment by blac-siren** [comment]
@asamisellah It's responsive

**Comment by Slinjez** [comment]
Pr is ok, nice simple UI, just a question, what font are you using? It looks good

**Pull request merged**
