### PR TITLE
#157889348 Create user can make a request.

### PR DESCRIPTION
**Pull request by blac-siren**
**What does this PR do?**
Implements a page where user can make request.

**Description of Task to be completed?**
A well designed sidebar that will allow user  sign out or go to dashboard.
A table where user can view all the request he/she made.

**How should this be manually tested?**
clone the repository into your local machine.
open your IDE
create a new branch
git checkout -b <new branch>
git fetch ft-user-make-request-157889348
open user_request.html into your browser.

**What are the relevant pivotal tracker stories?**
#157889348

**Screenshots (if available)**
image

### CODE REVIEW

**Comment by lawrenceChege** [comment]
I like the color scheme
The PR and commits are great too.
Good work

**Comment by lawrenceChege** [comment]
Yo could add a description for the request though

**Comment by Melvin1Atieno** [comment]
Good color choices, you could probably sync the colors for consistency, i.e, make the side nav part of the page. You could do this by probably having a footer with the same color as the side nav or any other inclusion you will find adaptable.

**Comment by asamisellah** [comment]
Simple clear form for request.

**Comment by janetnim** [comment]
i like how your page is quite simple and presentable

**Pull request merged**
