### PR TITLE
#157748804 Create page where user can view request

### PR DESCRIPTION
**Pull request by blac-siren**
**What does this PR do?**
Implements a page where user can view request.

**Description of Task to be completed?**
A well designed sidebar that will allow user sign out or go to dashboard.
A table where user can view all the request he/she made.

**How should this be manually tested?**
clone the repository into your local machine.
open your IDE
create a new branch
```
git checkout -b <new branch>
git fetch ft-user-dashboard-157748804
```
open user_dashboard.html into your browser

**What are the relevant pivotal tracker stories?**
#157748804

**Screenshots (if available)**
image

### CODE REVIEW

**Comment by lawrenceChege** [comment]
If it belongs to user, change Accept to accepted and reject to rejected . otherwise good work

**Comment by blac-siren** [comment]
@lawrenceChege thanks for the feedback. i'll work on it

**Comment by asamisellah** [comment]
Looks all good to me.

**Comment by janetnim** [comment]
yeah in the status check the tense....overall it looks good

**Pull request merged**
